import "./styles/global.scss";
import type { Metadata } from "next";
import localFont from 'next/font/local';

const grotesk = localFont({
  src: [
    {
      path: './../assets/fonts/cabinet/cabinet-grotesk-regular.otf',
      weight: '500',
      style: 'normal'
    },
    {
      path: './../assets/fonts/radio/radio-grotesk-regular.otf',
      weight: 'normal',
      style: 'normal'
    },
    {
      path: './../assets/fonts/cabinet/cabinet-grotesk-bold.otf',
      weight: 'bold',
      style: 'normal'
    },
  ]
})

export const metadata: Metadata = {
  title: "DevFest Ibadan 2023",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={grotesk.className}>{children}</body>
    </html>
  );
}
